### ISSUE TITLE
'passpie ubdate' is not working properly

### ISSUE THREAD

**Issue by jeffisabelle** [marcwebbie/passpie#100]
Hi, 

I have been using passpie for a while, recently I figured out that `passpie update` cli command is not working properly. I did test this on passpie version 1.4.1 on both mac and ubuntu. 

I manually dropped to the debugger and find out that the problem is on `database.py` in following lines;

    def update(self, fullname, values):
        values['fullname'] = make_fullname(values["login"], values["name"])
        values['modified'] = datetime.now()
        self.table().update(values, (where("fullname") == fullname))

here on the last line, we are querying the db with `fullname`, but we are passing the fullname parameter that `is not` went through make_fullname function. so changing the last line from this;

        self.table().update(values, (where("fullname") == fullname))

to this, 

        self.table().update(values, (where("fullname") == values['fullname']))

fixed the problem for me, but I'm not sure if this is the way it supposed to work. 

I have imported my database from an older version of passpie, that might cause the problem too. 

Thanks

**Comment by wakatara** [comment]
+1 Yup... this is definitely not updating for me.  =<

**Comment by marcwebbie** [comment]
Hello @jeffisabelle and @wakatara, 

Could you tell me what version of `passpie` you have installed and also, what are the commands you are running?

I've updated a credential successfully:

![screen shot 2016-05-22](https://cloud.githubusercontent.com/assets/2798771/15451992/69d36128-1fb4-11e6-9d21-5ab1c0b4e98a.png)

Thanks for opening this issue.

**Comment by marcwebbie** [comment]
Yes, 

I could reproduce this issue updating a credential passing only `name`:

```
passpie update bar
```

instead of full fullname:

```
passpie update foo@bar
```

Patched `1.4.2` is now on pypi(`pip install -U passpie`), and pull request submitted to [homebrew](https://github.com/Homebrew/homebrew-core/pulls)

Thanks for your contribution
