### ISSUE TITLE
passpie init waits forever after passphrase supplied

### ISSUE THREAD

**Issue by mmetince** [marcwebbie/passpie#102]
Hello,

This is very awkward. When I type passphrase code two times during database initialization, it start hanging on, forever... 

```
passpie init
Passphrase:
Type again:

```
How can I supply more debug log for further investigation ?

**Comment by marcwebbie** [comment]
Hello @mmetince 

Init takes a long time in some operation systems you can have more info on the documentation:

http://passpie.readthedocs.io/en/latest/faq.html#why-is-it-taking-so-long-to-initialize-a-database

Thanks for your contribution

**Comment by mmetince** [comment]
I'm sorry for creating ticket without documentation reading. Thank you for your reply.
