### ISSUE TITLE
Search does not find nested terms in subgroups (possibly a feature request)

### ISSUE THREAD

**Issue by wakatara** [marcwebbie/passpie#106]
When using passpie, I believe a common search behaviour would be searching for something in a subgroups (at least that's true for me). 
## Steps to Reproduce

Create new entries:

`passpie add foo@opensource/github --random`
`passpie add foo@opensource/python --random`

Search for github

`passpie search github`
## Observed Behaviour

returns nothing. 

`passpie search opensource`

returns both records though
## Expected Behaviour

`passpie search github`

should return the entry for

opensource/github.

(nb: I am giving this as an example as I keep running into it with my own home/   sing/   pt/  subgroups that i use.).

**Comment by marcwebbie** [comment]
Hello @wakatara 

Searches are regular expressions, you'd need to do something like this:

```
passpie search .*github
```

But you've made me see that this isn't clear on the [documentation](https://passpie.readthedocs.io/en/latest/getting_started.html#searching).

Thanks for your contribution
