### ISSUE TITLE
[v.1.5.1] passpie copy not recognising correct password

### ISSUE THREAD

**Issue by andrewvalentine** [marcwebbie/passpie#107]
```
[me@Host1] ~ > passpie --version                                             [Thu 7]
passpie, version 1.5.1
[me@Host1] ~ > passpie copy github                                           [Thu 7]
Passphrase:
Error: Wrong passphrase
[me@Host1] ~ >
```

```
[me@Host2] ~ > passpie --version                                         [Thu 7]
passpie, version 1.4.3
[me@Host2] ~ > passpie copy github                                       [Thu 7]
Passphrase:
Password copied to clipboard
[me@Host2] ~ >
```

My passpie database is kept in VCS. I've taken the following steps on `Host1`:

- Removed and re-cloned my passpie database
- Uninstalled and reinstalled via `brew`
- Uninstalled via `brew` and reinstalled via `pip`

With the same results.

To remedy this, I've downloaded the source of passpie v.1.4.3 and run `python setup.py install`. This seems to work, and `Host1` successfully reads my password from stdin again. I've run `brew pin passpie` on Host2 to keep my passpie version at 1.4.3.

Is this a known issue? Let me know if you need any further info.

**Comment by marcwebbie** [comment]
Hello @andrewvalentine 

This issue will be fixed in next version of passpie: https://github.com/Homebrew/homebrew-core/pull/2820

If you want to try with pip, `pip install -U passpie`

Thanks for your contribution

**Comment by andrewvalentine** [comment]
Hi @marcwebbie 

Thanks for this. Also, really appreciate your work on this excellent tool!

Cheers.

**Comment by marcwebbie** [comment]
Thanks @andrewvalentine and feel to open new issues, :)
