### ISSUE TITLE
You must use SystemRandom for password-generation

### ISSUE THREAD

**Issue by bjmc** [marcwebbie/passpie#108]
Hello,

I noticed you're [using rstr for creating password strings.](https://github.com/marcwebbie/passpie/blob/2222b0c56b44ab60c9d0dccdd2a657b622ce052c/passpie/utils.py#L15) If you want to use it for this application, you need to create an instance that relies on SystemRandom, as explained under "A Word of Caution" [here.](https://bitbucket.org/leapfrogdevelopment/rstr)

The default random number generator in Python is the Mersenne Twister and it is not secure for cryptographic applications. **This is a potentially serious security vulnerability.**

**Comment by marcwebbie** [comment]
Thanks for your contribution, any security contribution is highly appreciated
