### ISSUE TITLE
passpie and mcOS Sierra clipboard copy appears to not be working together

### ISSUE THREAD

**Issue by wakatara** [marcwebbie/passpie#111]
Sierra now has a "universal clipboard" which for some reason appears to not be working with passpie (which is a slight issue as this is how one gets one's passwords out of passpie.  =] ).

## Steps to Reproduce

1. Upgrade to Sierra  =p 
2. Attempt to access a standard password in the repository
3. Attempt to paste password in cleartext somewhere

```
🚀  ~ passpie copy home/router
Passphrase: <entered correctly>
Password copied to clipboard
```

Password that gets pasted is the one that should have been previously in the buffer.

## Expected behaviour

Password gets pasted into form correctly

## Observed Behaviour

Clipboard buffer is not updated in OS Sierra

I verified that my tmux and terminal are still copying passwords normally with my config (ie. using tmux vim-like ocpy bindings and with the standard highlight and cmd-C copy), so I _believe_ this is just an issue with passpie. I also disabled Alfred 3 while testing this (since it has a clipboard buffer I abuse regularly), but everything seems to point to an issue with passpie not passing things to the clipboard buffer in Sierra.

**Comment by wakatara** [comment]
Note: I also brew uninstalled did a cleanup and then brew installed passpie to get the sierra version of from homebrew and the problem still persists in terms of passwords not making it to the clipboard.

**Comment by wakatara** [comment]
Ignore: Sigh... after a lot more digging, this appears to be a regression issue with tmux not copying correctly to the pasteboard. 

Sorry for not spending more time drilling down on this. Since vim terminal usage and tmux copy worked, it was not clear to me that this was restrcited to a particular use case in tmux. 

For the sake of people having the same issue, the fixes to the problem for tmux are outlined here:
http://stackoverflow.com/questions/39645253/clipboard-failure-in-tmux-vim-after-upgrading-to-macos-sierra

**Comment by marcwebbie** [comment]
Hey @wakatara 

Thanks for the investigation, I should have checked if things were working properly on MacOSX Sierra by the way. Thanks for starting out. 😃
