### ISSUE TITLE
Wrong passphrase on Ubuntu

### ISSUE THREAD

**Issue by manzapanza** [marcwebbie/passpie#114]
I tried on Ubuntu 14 and Ubuntu 16 but when try to copy a password I always get the error `"Error: Wrong passphrase"`. I tested it on Ubuntu **14** and **16** and I haven't noticed differences between the two system versions. On my machine I has gpg 1.4.20 and gpg2 2.1.11. I tried also to create a link from gpg to gpg2, but I always get the same `"Error: Wrong passphrase"`.

```
➜  / passpie init --force
Passphrase:
Repeat for confirmation: 
Initialized database in /home/manzapanza/.passpie
➜  / passpie add massimo@test.com -r
➜  / passpie list                   
╒══════════╤═════════╤════════════╤═══════════╕
│ Name     │ Login   │ Password   │ Comment   │
╞══════════╪═════════╪════════════╪═══════════╡
│ test.com │ massimo │ ********   │           │
╘══════════╧═════════╧════════════╧═══════════╛
➜  / passpie copy test.com
Passphrase:
Error: Wrong passphrase
```

How can I get it to work? Some suggestions?
Thank you!

**Comment by MaximeLachere** [comment]
same probleme on Mint 18.1 (based on ubuntu 16)... Did you find a solution?

**Comment by xuelvming** [comment]
some here on ubuntu 16.04...Damn, I thought it's my fault to forge the root password  phrase

**Comment by scorphus** [comment]
Can you please check if #116 fixes this for you as well, if possible? Thanks

**Comment by MaximeLachere** [comment]
I check with #116 
The message "wrong passphrase" no longer appears. However, copy is not done. (there is no more error message) :(

**Comment by marcwebbie** [comment]
I am currently investigating this right now. Let me know if you have comments

**Comment by marcwebbie** [comment]
Latest patch release v.1.6.1 seems to have fixed this issue. I will be closing issue for now, feel free to reopen in case it persists.

**Comment by julianomadalena** [comment]
Hello! 

I'm having the same error. And I also can't set the first db.

<img width="228" alt="Captura de Tela 2019-06-04 às 23 41 39" src="https://user-images.githubusercontent.com/8068855/58926659-5965ea80-8722-11e9-90f6-7ceefb58d9a5.png">

I'm on Ubuntu
