### ISSUE TITLE
Feature Request: Integrate xkcdpass for password generation

### ISSUE THREAD

**Issue by wakatara** [marcwebbie/passpie#115]
While the random password generator works fine, I find I am trying to move towards easier to remember passwrods for when I do actually need to use them. The [xkcd comic on passwords](http://xkcd.com/936/) is, well... highly accurate. 

Anyhow, I've started using the rather awesome [xkcdpass password generator program](https://github.com/redacted/XKCD-password-generator) (in python btw) and thought it would make a great addition to passpie, which I ❤️  and obviously use way too much. =]

**Comment by wakatara** [comment]
Apparently the library can be imported into python code fairly easily: 

```
from xkcdpass import xkcd_password as xp

# create a wordlist from the default wordfile
# use words between 5 and 8 letters long
wordfile = xp.locate_wordfile()
mywords = xp.generate_wordlist(wordfile=wordfile, min_length=5, max_length=8)

# create a password with the acrostic "face"
print(xp.generate_xkcdpassword(mywords, acrostic="face"))
```

**Comment by marcwebbie** [comment]
Looks like there is an alternative from npm (https://www.npmjs.com/package/xkcd-password):

```
passpie add foo@bar --password="$(xkcd-password)"
```
