### ISSUE TITLE
Issues in Copy command on Windows 10

### ISSUE THREAD

**Issue by Suleman-Elahi** [marcwebbie/passpie#118]
The copy command doesn't seem to be working on my PC, running on Windows 10, build 16299.371. It always says "Wrong passphrase"

![image](https://user-images.githubusercontent.com/24384996/39109052-d5d2c6d6-46e8-11e8-8e3d-7201fd60b3c9.png)

**Comment by marcwebbie** [comment]
Latest patch release v.1.6.1 seems to have fixed this issue. I will be closing issue for now, feel free to reopen in case it persists.
