### ISSUE TITLE
Support for 1Password chrome extension

### ISSUE THREAD

**Issue by rainerborene** [marcwebbie/passpie#15]
I'm digging deep on how 1Password chrome extension protocol works. What do you think about pysswords supporting it? Btw, 1Password extension communicates with the 1Password Helper using web sockets.

**Comment by marcwebbie** [comment]
Hey @rainerborene 

You mean, Pysswords using the same protocol as 1Password?
Having browser extensions can be a good idea, maybe running adding "pysswords as a daemon" feature should do the trick. Those extensions would be other projects however.

I will keep this issue open as a feature for the time being.

Thank you

**Comment by marcwebbie** [comment]
Going to backlog, related to #7
