### ISSUE TITLE
passpie --version: Please install this project with setup.py or pip

### ISSUE THREAD

**Issue by jbd** [marcwebbie/passpie#35]
Hello,

I'm trying to use passpie on my debian testing and I cannot use pip --version:

```
$ python --version
Python 2.7.9
$ virtualenv passpie
$ source passpie/bin/activate
(passpie)$ pip install --upgrade https://github.com/marcwebbie/passpie/tarball/master
(passpie)$ which passpie
/home/jbd/tmp/passpie/bin/passpie
```

pip --version does not work :

```
(passpie)$ passpie --version
passpie, version Please install this project with setup.py or pip
```

**Comment by marcwebbie** [comment]
Hello @jbd 

Did you manage to get passpie running? Is passpie --version the only trouble you experiencing?

Could you tell me what is the output of the following commands:

```
which python
```

and

```
echo $PATH
```

**Comment by jbd** [comment]
All clear now :

passpie, version 0.1.2
$ pip install -U passpie^C
$ which python
/home/jbd/tmp/passpie/bin/python
$ which passpie
/home/jbd/tmp/passpie/bin/passpie
$ passpie --version
passpie, version 0.1.2

**Comment by marcwebbie** [comment]
Perfect then. :smile: 

Thanks for your contribution.
