### ISSUE TITLE
passpie init: hangs after passphrase confirmation

### ISSUE THREAD

**Issue by jbd** [marcwebbie/passpie#37]
Hello,

I'm trying to use passpie on my debian testing and passpie init hangs after passphrase confirmation
```
$ python --version
Python 2.7.9
$ virtualenv passpie
$ source passpie/bin/activate
(passpie)$ pip install --upgrade https://github.com/marcwebbie/passpie/tarball/master
(passpie)$ which passpie
/home/jbd/tmp/passpie/bin/passpie
```

The program hangs after passphrase confirmation:

```
(passpie)$ passpie init
Passphrase: 
Repeat for confirmation: 
```

**Comment by marcwebbie** [comment]
Hello @jbd 

It takes a while sometime to generate gpg keys because of entropy. It depends a lot on the system state: 

http://serverfault.com/questions/471412/gpg-gen-key-hangs-at-gaining-enough-entropy-on-centos-6

Thanks

**Comment by jbd** [comment]
Thank you for your answer. I was misusing rngd. Sorry for the useless issue.
