### ISSUE TITLE
Make it work with OS X keychain

### ISSUE THREAD

**Issue by ahmetalpbalkan** [marcwebbie/passpie#45]
First of all, great UI and idea! But it seems like many OS X users would simply rely on the encryption in their OS Keychain about their passwords etc rather than creating a separate DB. What do you think about this? Can `passpie` be considered as an alternative to "Keychain Access" GUI?

**Comment by marcwebbie** [comment]
`passpie` might support ordinary keychains, it might even be configurable on `.passpierc` for that if the user wishes so. For the moment this is not supported.

`passpie` creates a key pair and save it to the "database" where the credentials are saved for now.

Thanks for the idea, :)
