### ISSUE TITLE
Make filename extension `.pass` configurable

### ISSUE THREAD

**Issue by ratson** [marcwebbie/passpie#47]
It would be great if I could use `.gpg` for filename extension, so many existing tools could decrypt and view without further configration.

**Comment by marcwebbie** [comment]
I had this in mind when writing the storage: 

```
class PasspieStorage(Storage):
    extension = ".pass"
```

And it sounds pretty good. Tell me one thing, what applications you have in mind for using another extension like `.gpg` ?

**Comment by r4ts0n** [comment]
I often use Emacs to open gpg file to view the content, which will attempt to decrypt the file with `.gpg` extension.

Since `gpg -c myfile` is default to output `myfile.gpg`, it should generally more useful other program to interact with the file if it is gpg encrypted.
