### ISSUE TITLE
Homebrew issue 

### ISSUE THREAD

**Issue by bonbonpiment** [marcwebbie/passpie#52]
Hi 
Great concept ;)... Love it ! 
anyway it seems that there's no valid brew formula for passpie ... no install possible ...

**Comment by marcwebbie** [comment]
Before installing passpie, did you try:

```
brew update
```

**Comment by bonbonpiment** [comment]
yes , but without success , I 'll try tomorrow ;) ... may be a simple
homebrew server issue ... dunno !
Thanks for your reply and great work by the way ! Definitely a tool i will
use everyday ...

2015-06-02 20:09 GMT+02:00 Marc Webbie <notifications@github.com>:

**Comment by marcwebbie** [comment]
Hello @bonbonpiment,

What is the output of `brew update`?

Thanks for the feedback.

**Comment by bonbonpiment** [comment]
simply :

"Already up-to-date."

2015-06-02 21:48 GMT+02:00 Marc Webbie <notifications@github.com>:

**Comment by bonbonpiment** [comment]
just in case I dit a try on my laptop and everything's ok ! A crazy mystery
, same brew install on both computer , both up-to-date , same OS but the
first one did not accept the brew command, i still don't know why ! But It
s definitely no concern of Homebrew !
Thanks for the time you spent to answer my problem ;) ...

2015-06-02 22:00 GMT+02:00 christophe choppé <christophe@bonbonpiment.com>:

**Comment by marcwebbie** [comment]
Thanks @bonbonpiment 

I will be closing this issue for now.

PS: +1 pour le pseudo.
