### ISSUE TITLE
ImportError: No module named tinydb.queries

### ISSUE THREAD

**Issue by nattyseydi** [marcwebbie/passpie#58]
Hi,

I installed passpie with pip install passpie, when do passpie in the termianl I get this error message

Traceback (most recent call last):
  File "/usr/local/bin/passpie", line 7, in <module>
    from passpie.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/passpie/cli.py", line 8, in <module>
    from tinydb.queries import where
ImportError: No module named tinydb.queries

THanks

**Comment by marcwebbie** [comment]
What is installed passpie version?

```
passpie --version
```

What is the output of this:

```
python -c "import tinydb"
```

Have you had any error on installation?

**Comment by nattyseydi** [comment]
Hi,

This is what I get when I do passpie --version

Traceback (most recent call last):
  File "/usr/local/bin/passpie", line 7, in <module>
    from passpie.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/passpie/cli.py", line 8, in <module>
    from tinydb.queries import where
ImportError: No module named tinydb.queries

When I do python -c "import tinydb"
I get this
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tinydb

in the log file 

i686-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/tmp/env/include/python3.4m -c ext/_yaml.c -o build/temp.linux-i686-3.4/ext/_yaml.o

ext/_yaml.c:8:22: fatal error: pyconfig.h: No such file or directory

 #include "pyconfig.h"

                      ^

compilation terminated.

error: command 'i686-linux-gnu-gcc' failed with exit status 1

Cleaning up...
  Removing temporary dir /tmp/env/build...
Command /tmp/env/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/env/build/PyYAML/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-92ea48w_-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/env/include/site/python3.4 failed with error code 1 in /tmp/env/build/PyYAML
Exception information:
Traceback (most recent call last):
  File "/tmp/env/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/tmp/env/lib/python3.4/site-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/tmp/env/lib/python3.4/site-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/tmp/env/lib/python3.4/site-packages/pip/req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/tmp/env/lib/python3.4/site-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command /tmp/env/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/env/build/PyYAML/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-92ea48w_-record/install-record.txt --single-version-externally-managed --compile --install-headers /tmp/env/include/site/python3.4 failed with error code 1 in /tmp/env/build/PyYAML

Thanks

**Comment by nattyseydi** [comment]
Hi, the installion finally working but I have some problem to init passpie database
after a passpie init I got this
File "/usr/local/bin/passpie", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/passpie/cli.py", line 157, in init
    with Cryptor(config.path) as cryptor:
  File "/usr/local/lib/python2.7/dist-packages/passpie/crypt.py", line 38, in __init__
    self._gpg = gnupg.GPG(binary=self._binary, homedir=self._homedir)
TypeError: __init__() got an unexpected keyword argument 'binary'

**Comment by marcwebbie** [comment]
You've probably have the unexpected version of python-gnupg, try that:

```bash
pip uninstall python-gnupg
pip install -U passpie
```

> More info on the README: https://github.com/marcwebbie/passpie#typeerror-init-got-an-unexpected-keyword-argument-binary

**Comment by marcwebbie** [comment]
@nattyseydi any news on this issue?

**Comment by nattyseydi** [comment]
Hi,

I still have the same issue, I did everything you told 

Thanks

**Comment by marcwebbie** [comment]
Hello @nattyseydi,

Do you still experience this issue with latest versions of passpie?

**Comment by nattyseydi** [comment]
Hello

Everything is still fine. No new other issues

Thanks

On Tue, Sep 29, 2015 at 2:23 AM, Marc Webbie <notifications@github.com>
wrote:

> Hello @nattyseydi <https://github.com/nattyseydi>,
>
> Do you still experience this issue with latest versions of passpie?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marcwebbie/passpie/issues/58#issuecomment-143925588>.
>



-- 
Seydina Mouhamadou Ndiaye
Open Source Advocate
Front end Web developper - SysAdmin - Blogger
"The future belongs to those who prepare for it today."

http://nattyseydi.blogspot.com
http://twitter.com/NattySeydi

**Comment by marcwebbie** [comment]
Thanks and enjoy passpie.:)
