### ISSUE TITLE
[feature request]: Support generating password in given pattern.

### ISSUE THREAD

**Issue by huntzhan** [marcwebbie/passpie#62]
Allow user to input a regular expression, then the program could randomly generate a password with respect to the inputted pattern. For example, allowing user to supply a regular expression `[a-z]{3}[0-9]{3}[A-Z]{3}`, then the program could generate something like `mdj293EIR`.

**Comment by vitalk** [comment]
Hi @haoxun. Can you provide a use case for that scenario?

**Comment by haoxun** [comment]
In the case that user is familiar a pattern and try to remember some passwords in that pattern, this feature would be helpful.

**Comment by vitalk** [comment]
Thank you for clarification.

**Comment by marcwebbie** [comment]
Sounds like a good feature,

I use some kind of mental pattern to create my passwords as well.

**Comment by huntzhan** [comment]
amazing!
