### ISSUE TITLE
[Feature Request] Add 2 Factor Authentications

### ISSUE THREAD

**Issue by athrabeth** [marcwebbie/passpie#66]
I wanted to be able to log into my gmail, which has 2 factor authentication on it, but i didn't want to have to keep reaching for my cellphone. To that end I've hacked something together to retrieve a 2-factor authentication key stored in passpie and then pass that into [onetimepass](https://github.com/tadeck/onetimepass), then put that token into the clipboard the way passpie would. This would be helpful feature. Passpie eliminates the potentially insecure aspect of having your computer be responsible for two factor authentication, and its HELLA convenient. 

example: 
https://gist.github.com/athrabeth/1f44cce1bb615bcf3185

**Comment by marcwebbie** [comment]
Nice script, and great feature.

I didn't test it, but you could do something using **passpie** lib:

```python
import getpass
import onetimepass as otp
import os

from passpie import clipboard
from passpie.crypt import Cryptor
from passpie.database import Database
from passpie.cli import get_credential_or_abort

try:
    input = raw_input
except NameError:
    pass


passphrase = getpass.getpass("passphrase: ")
fullname  = input("fullname: ")
dbpath = os.path.expanduser('~/.passpie')
db = Database(dbpath)
credential = get_credential_or_abort()
with Cryptor(path=dbpath) as cryptor:
    key = cryptor.decrypt(credential.get['password'], passphrase=passphrase)

code = otp.get_totp(key)
clipboard.copy(str(code))
```

**Comment by marcwebbie** [comment]
Passpie new version isn't compatible with those snippets. I will be closing this issue for now. Feel free to open a new if needed.

Thanks for your colaboration
