### ISSUE TITLE
Browser integration

### ISSUE THREAD

**Issue by comtom** [marcwebbie/passpie#7]
It would be nice to add an API interface, so a browser extension can access to DB data and autofill forms, just like lastpass but locally. Do you think it's possible to add this feature to the roadmap?

**Comment by marcwebbie** [comment]
Hello @comtom 

There is already an API. The API is in python. You can check [database.py](https://github.com/marcwebbie/pysswords/blob/master/pysswords/db/database.py). However integrate with a browser you'd need a web server that runs Python and have GPG installed there as well.

It may be in the roadmap to have a web-server code so you can run your own web-server locally and have a plugin which handle does requests.

On the other hand having a browser plugin is likely to make your pyssword database less secure.

**Comment by marcwebbie** [comment]
Hello @comtom 

Not sure if it is worth doing browser integration for now. I will be closing the issue. Feel free to open new ones if you still think it is relevant.

Thanks
