### ISSUE TITLE
[Feature request] Destroy clipboard password after n seconds

### ISSUE THREAD

**Issue by wesjon** [marcwebbie/passpie#71]
I feel like having to clear my password from the clipboard after using the command `passpie copy [credential]` is a little inconvenient. 

Taking in consideration most users will need their password on the clipboard for a short period of time just to fill a login form I would like to suggest a feature aiming convenience and security.

1. Add a default timeout to the `passpie copy` command configurable through global settings.
2. Add a parameter `destroy` to `passpie copy` that clears the clipboard after n seconds

In my head it would work this way:

`passpie copy Google --destroy 10`
`passpie: copied your password to clipboard`
`passpie: clearing clipboard in 10 seconds`
`passpie: clipboard cleared`

**Comment by marcwebbie** [comment]
@wesjon Thanks for opening the feature request. It sounds like a great feature to have.

I was thinking about something like this:

```
passpie copy foo@bar --clear 10
```

**Comment by wesjon** [comment]
I agree - `clear` sounds more appropriate. `destroy` may cause some confusion.
