### ISSUE TITLE
Support for git remotes and automatic check for changes

### ISSUE THREAD

**Issue by gionn** [marcwebbie/passpie#72]
Hi,

I've manually configured a remote git origin and pushed.

Then my collegue just ran git clone ssh://blabla/passpie.git ~/.passpie and it works.

It would be nice to integrate the remote management directly in passpie, and maybe to automatically push after changing the database, and automatically pulling when accessing it.

**Comment by marcwebbie** [comment]
Hello @gionn,

Sounds interesting, but it might be a security flaw to push automatically.

I guess you could achieve the same thing using [git-hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). Automatically pulling on the other hand sounds interesting but also dangerous because of possible conflicts. 

Could you develop more a user case for that?

Thanks.

**Comment by gionn** [comment]
We are a small team of developers, and we always need to share some logins for external services (aws, rackspace, mailchimp, etc).

I understood that passpie was created to be used only for a single user on a local workstation, but why not extend it to multiple users?

A failed merge can happen, but it's really uncommon that two developers will add different credentials for the same service at the same time, so it may be address later.

Indeed, a post-commit hook will be fine to do a git push, but it may needs a git pull before.

Thanks.

**Comment by marcwebbie** [comment]
Oh nice way of using `Passpie`, I didn't think about that use case when starting the project. :)

Having automatic git pull sounds like a great configurable(`.passpierc`) feature in this case.
For now you might be able to get automatic pull using an alias:

```
alias passpie="git -C ~/.passpie pull; passpie"
```

Thanks.

**Comment by fernand0** [comment]
Hello,

I was thinking about a similar scenario: storing my credentials in different computers (laptop, other desktop,...). I'm not sure if it would be more secure to have several passpie repositories with different keys and so on in different computers or to use the same replicated passpie repository with the same key. Any ideas? Suggestions?
