### ISSUE TITLE
Add lastpass importer

### ISSUE THREAD

**Issue by comtom** [marcwebbie/passpie#74]
It would be nice to have an importer from lastpass too. 

The export format from lastpass is CSV, with the following fields:
url,username,password,extra,name,grouping,fav

Where:
extra is like a note related to the account,
name is the display name,
grouping is the name of the group (in lastpass interface this field shows up like "folder")
fav is a boolean field (1 if tagged as favourite, 0 if not)

Examples:
https://www.facebook.com/,user@example.com,PASSWORD,,my facebook account,Social,0
https://my.appcelerator.com/auth,user@example.com,PASSWORD,,my.appcelerator.com,,0

Thanks for having this in consideration. Cheers!

**Comment by marcwebbie** [comment]
I am now working on rewritting some of core dependencies of `passpie` and fixing bugs. 

It looks like a straightforward  to parse the generated csv from lastpass. I will try to add it up on the next version.

Thanks for opening this issue.

Regards

**Comment by marcwebbie** [comment]
Hello @comtom 

We now have a default CSV importer that we can map to columns in an CSV file to import. For example for a CSV like this `passwords.csv`:

```
"Group","Title","Username","Password","URL","Notes"
"Root","Some Title","john.doe","secret","example.com","Some comments"
"Root","Another title","foo.bar","p4ssword","example.org",""
```

We can import the credentials with:

```bash
passpie import --cols ",,login,password,name,comment" passwords.csv
```

Would that be a solution to this issue?

More info on the docs: http://passpie.readthedocs.org/en/latest/getting_started.html#importing-a-passpie-database

Thanks for your contribution. :smiley:

**Comment by comtom** [comment]
Awesome! I think it is. I will try it.
Thanks!

**Comment by marcwebbie** [comment]
Hey @comtom 

I will be closing this issue for now, I will assume it is fixed with passpie csv importer. Feel free to reopen the issue if needed.

Thanks for your contribution.
