### ISSUE TITLE
[feature request] Add an optional encrypted field and support vim editing.

### ISSUE THREAD

**Issue by huntzhan** [marcwebbie/passpie#87]
It seems that only login passwords could be stored into passpie. Adding an optional encrypted field could make passpie more flexible. For example, things like recovery email address and rsa private key could be stored to the optional field.

**Comment by marcwebbie** [comment]
Hellow @huntzhan 

This sounds interesting but how exactly would you handle adding, updating, querying?

Would that be something like this:

```
passpie add foo@example.com --additional "something goes here"
```

Thanks for your contribution

**Comment by huntzhan** [comment]
@marcwebbie Maybe similar to the way of [pass-store](http://www.passwordstore.org/), in which you can modify a file through an editor(i.e. vim).

By typing following command:

```
passpie update foo@example.com --additional
```

An editor will pop up just like the effect of `git commit -a` or `crontab -e`.
