### ISSUE TITLE
Latest version on Homebrew is 1.3.1

### ISSUE THREAD

**Issue by krzkrzkrz** [marcwebbie/passpie#95]
Any chance we can have the new version up on Homebrew?

**Comment by marcwebbie** [comment]
Hello @krzkrzkrz 

Pull request is now open: https://github.com/Homebrew/homebrew/pull/49225, 

thanks for contributing.

**Comment by marcwebbie** [comment]
Passpie is now 1.4.1 on home brew. Thanks
