### ISSUE TITLE
Does anyone have a script to import from keepassx?

### ISSUE THREAD

**Issue by krzkrzkrz** [marcwebbie/passpie#96]
With keepassx, I can export to csv or text. Anyone have a script I can use to parse through the exported csv or text file?

**Comment by marcwebbie** [comment]
Did you see the documentation on keepass importing?

http://passpie.readthedocs.org/en/latest/getting_started.html#importing-credentials

**Comment by marcwebbie** [comment]
Hello @krzkrzkrz 

Did csv importing worked out for you?

Thanks for your contribtution

**Comment by marcwebbie** [comment]
I will be closing this issue for now, I am assuming you manage to import using passpie csv importer. ;)
